version: jp
build_path: build/jp
asm_path: asm/jp
asset_path: assets/jp
src_path: src
ld_script_path: build/jp
generated_sym_path: build/jp
align: 4
subalign: 4
overlays:
  - name: another
    disk_path: disk/jp/SLPS_016.55
    sha1: 5f4f77b1eb743e92564008b24a98efa8e8d317d6
    base_path: ""
    symbol_addrs_path:
      - config/symbols.another.jp.txt
    migrate_rodata_to_functions: true
    vram_start: 0x80010000
    gp_value: 0x80061a1c
    code_segments:
      - name: main
        start: 0x800
        vram: 0x80010000
        subsegments:
          - [0x800, rodata]
          - [0x2FAC, c, main/main]
          - [0x3BB8, c, main/name_entry]
          - [0x6CA4, c, main/chapter_title]
          - [0x8268, c, main/title]
          - [0x9C60, c, main/cd_stream]
          - [0xC664, c, main/script]
          - [0x1E648, c, main/akao]
          - [0x2946C, c, main/psxsdk]
          - [0x36F48, c, main/movie]
          - [0x39FD8, data]
          - [0x5221C, sdata]
          - [0x527B8, sbss]
          - [0x527C0, bss]
      - name: engine
        start: 0xD53B0
        vram: 0x800E4BB0
        subsegments:
          - [0xD53B0, rodata]
          - [0xD5CE8, c, engine/vram_cache]
          - [0xD9120, c, engine/portrait_anim]
          - [0xDC620, c, engine/taiwa]
          - [0xE4CA8, c, engine/demo_menu]
          - [0xEACF8, c, engine/memcard]
          - [0xEF640, c, engine/portrait_select]
          - [0xF35C8, c, engine/game_loop]
          - [0xFD390, data]
          - [0xFD9B0, bss]
