version: jp
build_path: build/jp
asm_path: asm/jp
asset_path: assets/jp
src_path: src
ld_script_path: build/jp
generated_sym_path: build/jp
align: 4
subalign: 4
overlays:
  - name: another
    disk_path: disk/jp/SLPS_016.55
    sha1: 5f4f77b1eb743e92564008b24a98efa8e8d317d6
    base_path: ""
    symbol_addrs_path:
      - config/symbols.another.jp.txt
    migrate_rodata_to_functions: true
    vram_start: 0x80010000
    gp_value: 0x80061a1c
    code_segments:
      - name: main
        start: 0x800
        vram: 0x80010000
        subsegments:
          - [0x800, rodata]
          - [0x2FAC, c, main]
          - [0x3BB8, c, name_entry]
          - [0x6CA4, c, chapter_title]
          - [0x8268, c, title]
          - [0x9C60, c, cd_stream]
          - [0xC664, c, script]
          - [0x1E648, c, akao]
          - [0x24340, c, graphics]
          - [0x2946C, c, psxsdk]
          - [0x36F48, c, movie_hw]
          - [0x39FD8, data]
          - [0x5221C, sdata]
          - [0x527B8, sbss]
          - [0x527C0, bss]
      - name: engine
        start: 0xD53B0
        vram: 0x800E4BB0
        subsegments:
          - [0xD53B0, rodata]
          - [0xD5CE8, c, vram_cache]
          - [0xD9120, c, portrait_anim]
          - [0xDC620, c, taiwa_ui]
          - [0xE4CA8, c, demo_menu]
          - [0xEACF8, c, memcard]
          - [0xEF640, c, portrait_select]
          - [0xF35C8, c, game_loop]
          - [0xFD390, data]
          - [0xFD9B0, bss]
