#ifndef AKAO_H
#define AKAO_H

#include "common.h"

#define AKAO_MAGIC 0x4F414B41

#define AKAO_PAN_LEFT 0x00
#define AKAO_PAN_CENTER 0x40
#define AKAO_PAN_RIGHT 0x7F
#define AKAO_PAN_MAX 0x7F
#define AKAO_VOL_MAX 0x7F

#define AKAO_SFX_SLOT_0 0x30
#define AKAO_SFX_SLOT_1 0x32
#define AKAO_SFX_SLOT_2 0x34
#define AKAO_SFX_SLOT_3 0x36

#define AKAO_MUSIC 0x0
#define AKAO_SOUND 0x1
#define AKAO_MENU 0x2

#define AKAO_STEREO 0x1
#define AKAO_MONO 0x2
#define AKAO_STEREO_CHANNELS 0x4

#define AKAO_SFX_LEGATO 0x1
#define AKAO_SFX_FULL_LENGTH 0x4

#define AKAO_CONTROL_PAUSE_MUSIC_UPDATE 0x001
#define AKAO_CONTROL_PAUSE_UPDATE 0x002
#define AKAO_CONTROL_REVERB_ENABLE 0x010
#define AKAO_CONTROL_STATE_SAVED 0x100

#define AKAO_UPDATE_SPU_VOICE (SPU_VOICE_VOLL | SPU_VOICE_VOLR)
#define AKAO_UPDATE_SPU_ADSR                                                                                           \
    (SPU_VOICE_ADSR_AMODE | SPU_VOICE_ADSR_SMODE | SPU_VOICE_ADSR_RMODE | SPU_VOICE_ADSR_AR | SPU_VOICE_ADSR_DR |      \
     SPU_VOICE_ADSR_SR | SPU_VOICE_ADSR_RR | SPU_VOICE_ADSR_SL)
#define AKAO_UPDATE_SPU_BASE_WOR                                                                                       \
    (SPU_VOICE_WDSA | SPU_VOICE_ADSR_AMODE | SPU_VOICE_ADSR_SMODE | SPU_VOICE_ADSR_AR | SPU_VOICE_ADSR_DR |            \
     SPU_VOICE_ADSR_SR | SPU_VOICE_ADSR_SL | SPU_VOICE_LSAX)
#define AKAO_UPDATE_SPU_BASE (AKAO_UPDATE_SPU_BASE_WOR | SPU_VOICE_ADSR_RMODE | SPU_VOICE_ADSR_RR)
#define AKAO_UPDATE_SPU_ALL (AKAO_UPDATE_SPU_BASE | AKAO_UPDATE_SPU_VOICE | SPU_VOICE_PITCH)

#define AKAO_UPDATE_VIBRATO 0x1
#define AKAO_UPDATE_TREMOLO 0x2
#define AKAO_UPDATE_PAN_LFO 0x4
#define AKAO_UPDATE_DRUM_MODE 0x8
#define AKAO_UPDATE_SIDE_CHAIN_PITCH 0x10
#define AKAO_UPDATE_SIDE_CHAIN_VOL 0x20
#define AKAO_UPDATE_VOICE_EFFECT 0x40
#define AKAO_UPDATE_REVERB_DEPTH 0x80
#define AKAO_UPDATE_OVERLAY 0x100
#define AKAO_UPDATE_ALTERNATIVE 0x200
#define AKAO_UPDATE_VOICE_BUS 0x100000
#define AKAO_UPDATE_ADSR_AR 0x1000000
#define AKAO_UPDATE_ADSR_SR 0x8000000
#define AKAO_UPDATE_ADSR_RR 0x10000000

#define AKAO_UPDATE_LFO_MASK                                                                                           \
    (AKAO_UPDATE_VIBRATO | AKAO_UPDATE_TREMOLO | AKAO_UPDATE_PAN_LFO | AKAO_UPDATE_SIDE_CHAIN_PITCH |                  \
     AKAO_UPDATE_SIDE_CHAIN_VOL)

#define AKAO_UPDATE_NOISE_CLOCK 0x10
#define AKAO_UPDATE_REVERB 0x80
#define AKAO_UPDATE_VOICE_MODES 0x100

typedef struct {
    /* 0x00 */ s32 stereoMode;
    /* 0x04 */ s32 updateFlags;
} AkaoControl;

extern AkaoControl g_AkaoControl;

void AkaoUpdateNoiseVoices(void);
void AkaoUpdateReverbVoices(void);
void AkaoUpdatePitchLfoVoices(void);
void AkaoStopStream(void);

// Sequence opcodes (0xA0..0xFF)
#define AKAO_OP_FINISH_CHANNEL 0xA0
#define AKAO_OP_LOOP_RETURN 0xCA

typedef enum {
    AKAO_PLAY_MUSIC = 0x10,
    AKAO_PLAY_MUSIC_SAVE_CURR = 0x14,
    AKAO_PLAY_MUSIC_SWAP_SAVED = 0x15,
    AKAO_FADE_PLAY_MUSIC = 0x18,
    AKAO_FADE_PLAY_MUSIC_SAVE_CURR = 0x19,
    AKAO_PLAY_SOUND = 0x20,
    AKAO_PLAY_TWO_SOUNDS = 0x21,
    AKAO_PLAY_THREE_SOUNDS = 0x22,
    AKAO_PLAY_FOUR_SOUNDS = 0x23,
    AKAO_PLAY_ONE_CONSECUTIVE_SOUND = 0x24,
    AKAO_PLAY_TWO_CONSECUTIVE_SOUNDS = 0x25,
    AKAO_PLAY_THREE_CONSECUTIVE_SOUNDS = 0x26,
    AKAO_PLAY_FOUR_CONSECUTIVE_SOUNDS = 0x27,
    AKAO_PLAY_SLOT2 = 0x28, // Alias for AKAO_PLAY_SOUND
    AKAO_PLAY_SLOT1 = 0x29,
    AKAO_PLAY_SLOT0 = 0x2A,
    AKAO_PLAY_SLOT3 = 0x2B,
    AKAO_PLAY_MENU_SOUND = 0x30,
    AKAO_PLAY_DIRECT = 0x34,
    AKAO_SAVE_CHANNEL_STATE = 0x40,
    AKAO_SET_STEREO_MODE = 0x80,
    AKAO_SET_MONO_MODE = 0x81,
    AKAO_RESET_VOLUME = 0x82,
    AKAO_SET_MUTE_MUSIC_MASK = 0x90,
    AKAO_SET_CONDITION = 0x92,
    AKAO_FLUSH_ALL_PENDING_UPDATES = 0x98,
    AKAO_APPLY_ALL_PENDING_UPDATES = 0x99,
    AKAO_FLUSH_PENDING_MUSIC_UPDATES = 0x9A,
    AKAO_APPLY_PENDING_MUSIC_UPDATES = 0x9B,
    AKAO_FLUSH_PENDING_SFX_UPDATES = 0x9C,
    AKAO_APPLY_PENDING_SFX_UPDATES = 0x9D,
    AKAO_SET_VOL_BALANCE_SLOT2 = 0xA0,
    AKAO_SET_VOL_BALANCE_SLOT1 = 0xA1,
    AKAO_SET_VOL_BALANCE_SLOT0 = 0xA2,
    AKAO_SET_VOL_BALANCE_SLOT3 = 0xA3,
    AKAO_SLIDE_VOL_BALANCE_SLOT2 = 0xA4,
    AKAO_SLIDE_VOL_BALANCE_SLOT1 = 0xA5,
    AKAO_SLIDE_VOL_BALANCE_SLOT0 = 0xA6,
    AKAO_SLIDE_VOL_BALANCE_SLOT3 = 0xA7,
    AKAO_SET_PAN_SLOT2 = 0xA8,
    AKAO_SET_PAN_SLOT1 = 0xA9,
    AKAO_SET_PAN_SLOT0 = 0xAA,
    AKAO_SET_PAN_SLOT3 = 0xAB,
    AKAO_SLIDE_PAN_SLOT2 = 0xAC,
    AKAO_SLIDE_PAN_SLOT1 = 0xAD,
    AKAO_SLIDE_PAN_SLOT0 = 0xAE,
    AKAO_SLIDE_PAN_SLOT3 = 0xAF,
    AKAO_SET_PITCH_SLOT2 = 0xB0,
    AKAO_SET_PITCH_SLOT1 = 0xB1,
    AKAO_SET_PITCH_SLOT0 = 0xB2,
    AKAO_SET_PITCH_SLOT3 = 0xB3,
    AKAO_SLIDE_PITCH_SLOT2 = 0xB4,
    AKAO_SLIDE_PITCH_SLOT1 = 0xB5,
    AKAO_SLIDE_PITCH_SLOT0 = 0xB6,
    AKAO_SLIDE_PITCH_SLOT3 = 0xB7,
    AKAO_SET_ALL_VOL_BALANCE = 0xB8,
    AKAO_SLIDE_ALL_VOL_BALANCE = 0xB9,
    AKAO_SET_ALL_PAN = 0xBA,
    AKAO_SLIDE_ALL_PAN = 0xBB,
    AKAO_SET_ALL_PITCH = 0xBC,
    AKAO_SLIDE_ALL_PITCH = 0xBD,
    AKAO_VOLUME_SET = 0xC0,
    AKAO_VOL_SLIDE_FROM_CURR = 0xC1,
    AKAO_VOL_SLIDE_BETWEEN_TARGETS = 0xC2,
    AKAO_SET_CD_VOL = 0xC8,
    AKAO_CD_VOL_SLIDE_FROM_CURR = 0xC9,
    AKAO_CD_VOL_SLIDE_BETWEEN_TARGETS = 0xCA,
    AKAO_OP_LEGATO_ON = 0xCC,
    AKAO_OP_LEGATO_OFF = 0xCD,
    AKAO_SET_TEMPO = 0xD0,
    AKAO_OP_FULL_LENGTH_ON = 0xD0,
    AKAO_TEMPO_SLIDE_FROM_CURR = 0xD1,
    AKAO_OP_FULL_LENGTH_OFF = 0xD1,
    AKAO_TEMPO_SLIDE_BETWEEN_TARGETS = 0xD2,
    AKAO_SET_PITCH = 0xD4,
    AKAO_OP_SIDE_CHAIN_PLAYBACK_ON = 0xD4,
    AKAO_PITCH_SLIDE_FROM_CURR = 0xD5,
    AKAO_OP_SIDE_CHAIN_PLAYBACK_OFF = 0xD5,
    AKAO_PITCH_SLIDE_BETWEEN_TARGETS = 0xD6,
    AKAO_OP_SIDE_CHAIN_PITCH_VOL_ON = 0xD6,
    AKAO_OP_SIDE_CHAIN_PITCH_VOL_OFF = 0xD7,
    AKAO_SET_TEMPO_AND_PITCH = 0xD8,
    AKAO_TEMPO_AND_PITCH_SLIDE_FROM_CURR = 0xD9,
    AKAO_TEMPO_AND_PITCH_SLIDE_BETWEEN_TARGETS = 0xDA,
    AKAO_SET_REVERB_PAN = 0xE0,
    AKAO_OP_VOICE_BUS_ROUTING_ON = 0xE0,
    AKAO_STOP_STREAM = 0xE2,
    AKAO_SET_REVERB_MUL = 0xE4,
    AKAO_STOP_MUSIC = 0xF0,
    AKAO_STOP_ALL_SOUNDS = 0xF1,
    AKAO_CLEAR_SAVED_MUSIC0 = 0xF2,
    AKAO_CLEAR_SAVED_MUSIC1 = 0xF3,
    AKAO_SAVE_STATE = 0xF4,
    AKAO_RESTORE_STATE = 0xF5,
    AKAO_STREAM_REVERB_MASK_CLEAR = 0xF8,
    AKAO_STREAM_REVERB_MASK_RESTORE = 0xF9,
} AkaoCommands;

#define SPU_VOICE_REG(voice, offset) (*(volatile u16*)(0x1F801C00 + (offset) + ((voice) * 0x10)))
#define SPU_VOICE_REG8(voice, offset) (*(volatile u8*)(0x1F801C00 + (offset) + ((voice) * 0x10)))

// Voice channel register offsets (from 0x1F801C00 base)
#define SPU_VOICE_VOL_L_OFFSET 0x00
#define SPU_VOICE_VOL_R_OFFSET 0x02
#define SPU_VOICE_PITCH_OFFSET 0x04
#define SPU_VOICE_START_ADDR_OFFSET 0x06
#define SPU_VOICE_ADSR_AMODE_OFFSET 0x08
#define SPU_VOICE_ADSR_SMODE_OFFSET 0x0A
#define SPU_VOICE_LOOP_ADDR_OFFSET 0x0E


#define SPU_REG(addr) (*(u16*)(addr))

// SPU Control Register Addresses
#define SPU_VOICE_KEY_ON_LO 0x1F801D88
#define SPU_VOICE_KEY_ON_HI 0x1F801D8A
#define SPU_VOICE_KEY_OFF_LO 0x1F801D8C
#define SPU_VOICE_KEY_OFF_HI 0x1F801D8E
#define SPU_VOICE_CHN_FM_LO 0x1F801D90
#define SPU_VOICE_CHN_FM_HI 0x1F801D92
#define SPU_VOICE_CHN_NOISE_LO 0x1F801D94
#define SPU_VOICE_CHN_NOISE_HI 0x1F801D96
#define SPU_VOICE_CHN_REVERB_LO 0x1F801D98
#define SPU_VOICE_CHN_REVERB_HI 0x1F801D9A
#define SPU_CD_VOL_L 0x1F801DB0
#define SPU_CD_VOL_R 0x1F801DB2

#endif
